### ISSUE TITLE
Avoid using request module

### ISSUE THREAD

**Issue by delvedor** [elastic/enterprise-search-node#7]
The [request](https://www.npmjs.com/package/request) module went in [maintenance mode](https://github.com/request/request/issues/3142), therefore it would be better to move to an actively maintained module.
Given that you support a pure promise API and you don't need to support callbacks, I would recommend [got](https://www.npmjs.com/package/got), it offers the same features with a native promise API.

**Comment by yakhinvadim** [comment]
Thank you, Tomas, this is a good suggestion. We are planning to do a refactoring of our clients soon, so this change will probably get into the next or the following release.
